version: '3'
services:
    backend:
        build:
            context: ./backend
            args:
                HERE_API_SECRET: hfdi-6Pzch71e2nTGd6Hrw_BkoNNAgU4DTv17PlBd7I
        ports:
            - "5000:5000"
        networks:
            - isolation-network

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        networks:
            - isolation-network

networks:
  isolation-network:
    driver: bridge